---
- hosts: all
  become: yes
  tasks:
  - name: update
    apt:
      update_cache: yes
  - name: nginx install
    apt:
      name: nginx
  - name: restart nginx
    service:
     name: nginx
     state: restarted

  - name: Creates directory
    file: 
      path: /etc/nginx/ssl 
      state: directory
      mode: 0755

      
  - name: nginx key and .crt
    command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt
 
  - name: Generate an OpenSSL private key
    openssl_privatekey:
      path: /etc/ssl/ansible.com.pem
  
  
  - name: Generate an OpenSSL Certificate Signing Request
    openssl_csr:
      path: /etc/ssl/nginx.csr
      Country Name: IN
      State or Province Name: TG
      Locality Name: HYD
      Organization Name: shravan
      Organizational Unit Name: shravan
      common_name: shravan
      email_address: mshravan986@gmail.com

  - name: Generate a Self Signed OpenSSL certificate
    openssl_certificate:
      path: /etc/ssl/crt/ansible.com.crt
      privatekey_path: /etc/ssl/ansible.com.pem
      csr_path: /etc/ssl/ansible.com.csr
      provider: selfsigned
